# Generated by Django 5.2.7 on 2025-10-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Location latitude for proximity matching",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Location longitude for proximity matching",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="max_distance_km",
            field=models.PositiveIntegerField(
                default=50, help_text="Maximum distance in kilometers for job matching"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills required for this job",
                related_name="job_postings",
                to="api.skill",
            ),
        ),
        migrations.AddField(
            model_name="skilledlaborer",
            name="max_travel_distance_km",
            field=models.PositiveIntegerField(
                default=25, help_text="Maximum travel distance in kilometers"
            ),
        ),
        migrations.AddField(
            model_name="skilledlaborer",
            name="preferred_latitude",
            field=models.FloatField(
                blank=True, help_text="Preferred location latitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="skilledlaborer",
            name="preferred_longitude",
            field=models.FloatField(
                blank=True, help_text="Preferred location longitude", null=True
            ),
        ),
    ]
