# Generated by Django 5.2.7 on 2025-10-22 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobposting_latitude_jobposting_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledlaborer',
            name='has_avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skilledlaborer',
            name='profile_completeness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
