# Generated by Django 5.2.7 on 2025-11-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_skilledlaborer_has_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("JOB_APPLICATION", "Job Application"),
                    ("APPLICATION_STATUS", "Application Status"),
                    ("NEW_JOB_POSTING", "New Job Posting"),
                    ("WORK_REMINDER", "Work Reminder"),
                    ("RATING_REMINDER", "Rating Reminder"),
                    ("ACCOUNT_UPDATE", "Account Update"),
                    ("LABORER_COORDINATOR_MESSAGE", "Laborer Coordinator Message"),
                    ("MESSAGE_SENT", "Message Sent"),
                    ("COORDINATOR_RESPONSE", "Coordinator Response"),
                ],
                max_length=50,
            ),
        ),
    ]
